# Generated by Django 2.0.5 on 2018-05-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TArticle',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('articleName', models.CharField(max_length=200)),
                ('articleContent', models.CharField(max_length=1000)),
                ('articlePic', models.ImageField(upload_to='')),
                ('dateCreated', models.DateTimeField()),
            ],
        ),
    ]
